### PR TITLE
EZP-25942: Fix errors specific to Microsoft Windows operating system

### PR DESCRIPTION
**Pull request by blankse**
Original PR: https://github.com/ezsystems/ezpublish-kernel/pull/1725

### CODE REVIEW

**Comment by emodric** [comment]
Thanks @blankse !

**Comment by blankse** [comment]
Can you make a new tag please? :)

**Comment by emodric** [comment]
Sure! Any more PRs besides #48 ? :)

**Comment by blankse** [comment]
Thanks :+1: 
No, not yet

**Comment by emodric** [comment]
@blankse Tagged `v14.12.9` https://github.com/netgen/ezpublish-kernel/releases/tag/v14.12.9 :)

**Pull request merged**
