### PR TITLE
see EZP-25529 fix preview

### PR DESCRIPTION
**Pull request by ernestob**
Hi guys
This pull request is to apply the patches to fix the preview from the legacy admin.

Original PR: https://github.com/ezsystems/LegacyBridge/pull/51

### CODE REVIEW

**Comment by emodric** [comment]
Hi @ernestob 

Thanks for this!

Can you please share a way how to trigger errors related to EZP-24691?

As for EZP-25529, you're right, preview does throw an error, but I'd appreciate if each of the mentioned issues are fixed in separate commits.

**Comment by bjko** [comment]
Hi,
this is related to EZP-25551

**Comment by emodric** [comment]
@bjko I see. But that's the same issue as EZP-25529, and I know the fix, I fixed it ;)

I was asking about EZP-24691, I would like to see some steps on how to replicate the issue, because I haven't seen the issue come up yet.

**Comment by ernestob** [comment]
Hi @emodric 

I was trying to apply the patch fix the error being thrown by the preview and yes you are right only **EZP-25529** is needed for this.

I will remove the patch for **EZP-24691** from this pull request, so  this can be merged into master.

**Comment by emodric** [comment]
@ernestob Thanks for this! Merging now!

**Pull request merged**
