### PR TITLE
Fix EZP-26393: Missing options for ezpublish_legacy.kernel_handler.cli

### PR DESCRIPTION
**Pull request by blankse**
Original PR: https://github.com/ezsystems/LegacyBridge/pull/70

### CODE REVIEW

**Comment by emodric** [comment]
Thanks! :)

**Comment by blankse** [comment]
@emodric Can you make a new Tag with this change?

**Comment by emodric** [comment]
Sure. Are there any more changes you'd like to see in before I tag?

**Comment by blankse** [comment]
No, not at the moment :)

**Comment by emodric** [comment]
Release done: https://github.com/netgen/ezpublish-kernel/releases/tag/v14.12.6

**Comment by blankse** [comment]
Thanks! :)

**Pull request merged**
