### PR TITLE
EZP-25100: Added common base for ContentCreateStruct / ContentUpdateStruct

### PR DESCRIPTION
**Pull request by blankse**
Original PR: https://github.com/ezsystems/ezpublish-kernel/pull/1504

### CODE REVIEW

**Comment by emodric** [comment]
Hi @blankse !

Thanks for this! However, is this really needed on 2014.11/12 ? As far as I understood, this is related to repo forms and Platform UI which does not work on this version anyhow. Are there any other usecases I'm not aware of?

**Comment by blankse** [comment]
Hi @emodric 
1. My PhpStorm shows me many erros because of the wrong property-write comments
2. It's nice to have the ContentStruct class for Type Hinting in my Import Commands

I see no BC break. So why not? :)

**Comment by emodric** [comment]
Makes sense :) Do you want to implement other common objects for other create structs (in this or other PR)?

**Comment by blankse** [comment]
I added following PRs:
https://github.com/ezsystems/ezpublish-kernel/pull/1398
https://github.com/ezsystems/ezpublish-kernel/pull/1408
https://github.com/ezsystems/ezpublish-kernel/pull/1429

Other useful classes such as ContentTypeStruct and FieldDefinitionStruct do not exist yet...

**Comment by emodric** [comment]
Thanks @blankse ! Give me couple of days to review and merge, please :)

**Comment by emodric** [comment]
P.S. There is a failing test now :)

**Comment by blankse** [comment]
It seems to be a time issue with publicationDate and modificationDate.
I think it is not related to this changes. I try again.

**Comment by emodric** [comment]
Looks good, thanks :)

**Pull request merged**
