### PR TITLE
[Composer] Fix conflict with Symfony version > 2.7.29

### PR DESCRIPTION
**Pull request by blankse**

### CODE REVIEW

**Comment by blankse** [comment]
@emodric Just upgrade the version is not enough. We must backport all changes from https://github.com/ezsystems/ezpublish-kernel/pull/2030

**Comment by emodric** [comment]
@blankse I don't see why using the later versions of PHPUnit 4 would break the build. If the problem are those deprecation errors, they could probably be solved by using `"symfony/phpunit-bridge": "^2.7"` in `require-dev`.

**Comment by blankse** [comment]
@emodric No, this doesn't solve the deprecation errors. The errors come from phpunit itself: https://github.com/sebastianbergmann/phpunit/blob/4.8/src/Framework/Assert.php#L2207

**Comment by emodric** [comment]
Okay, I found the solution.

This works at the top of `bootstrap.php` (together with Twig constraint at `^1.0` and PHPUnit at `~4.1.3`):

```php
if (!class_exists('PHPUnit\Framework\TestCase')) {
    class_alias('PHPUnit_Framework_TestCase', 'PHPUnit\Framework\TestCase');
}
```

**Comment by blankse** [comment]
@emodric Looks good :thumbsup:

**Comment by emodric** [comment]
Thanks @blankse :)

**Pull request merged**
