### PR TITLE
EZP-26071: Download asset binary only if we need to create a variation

### PR DESCRIPTION
**Pull request by blankse**
Original Commit: https://github.com/ezsystems/ezpublish-kernel/commit/96f15b1cb893da9dc2b84fac13389d2c8195732f

### CODE REVIEW

**Comment by blankse** [comment]
Bump PHPUnit version Original Commit: https://github.com/ezsystems/ezpublish-kernel/commit/a0a4763d9fa56a6382517fe5d0efba9d43f547da

**Comment by blankse** [comment]
I added an composer.lock file with twig version 1.33.2.
Version 1.34 needs PHPUnit 6.
The original repo has a composer.lock too.

**Comment by emodric** [comment]
@blankse Are you sure about that? 1.x version of Twig should work on PHPUnit 5.x, no matter which version. Only 2.x requires PHP 7.1 and PHPUnit 6.

Also, rather than adding a `composer.lock`, why don't you limit the Twig constraint in `composer.json`?

As for other changes, I'm vacationing today, so I'll take a look next week :)

**Comment by blankse** [comment]
@emodric Yes see here: https://github.com/twigphp/Twig/pull/2452 This is merged in the 1.x branch.

I can limit the twig constraint. I will change it :)

**Comment by emodric** [comment]
That PR means support for PHPUnit 5.4+ :) Namespaced PHPUnit classes are available since 5.4 :)

**Comment by blankse** [comment]
OK :) But we have version 4 ;)

**Comment by emodric** [comment]
Argh! You're right :)

Then Twig constraint is the way to go :) :+1:

**Comment by emodric** [comment]
Thanks @blankse :)

**Comment by emodric** [comment]
@blankse It seems there's an issue with limiting Twig to `< 1.34`. Symfony as of version 2.7.29 requires Twig 1.34 and above, which conflicts with the installation of latest version eZ kernel and the version before (14.12.10) is automatically installed instead.

Is there a way to allow Twig > 1.34?

**Comment by blankse** [comment]
So the composer.lock for tests was not too bad ;)
Otherwise we must backport this when it is finished I think: https://github.com/ezsystems/ezpublish-kernel/pull/2030

**Comment by emodric** [comment]
For tests, yes, but `composer.lock` would not be used when installing inside of eZ Publish Community Edition, so you would still get the conflict.

Did you try using `4.8.35` version of PHPUnit which has support for namespaced `TestCase`? I think that might solve your problem?

Basically, setting `phpunit/phpunit` to `^4.8.35` ?

**Comment by blankse** [comment]
We don't need the twig constraint with a composer.lock. So we would not get the conflict.
I test the phpunit update: https://github.com/netgen/ezpublish-kernel/pull/55

**Pull request merged**
