### PR TITLE
EZP-24213: FullText stopWordThreshold should be percentage of content count

### PR DESCRIPTION
**Pull request by blankse**
Original PR: https://github.com/ezsystems/ezpublish-kernel/pull/1218

### CODE REVIEW

**Comment by emodric** [comment]
Thanks @blankse !

If I understood correctly, this seems to be a BC break, right?.

**Comment by blankse** [comment]
If someone had overridden the searchThresholdValue configuration in the service arguments, it now has no effect.
I think everyone set it to a very hight value, because its not depending to the content count.
When the content count grow, words disappear from the search now.

Its a little BC break, but there will be no error.

**Comment by emodric** [comment]
I'm really comfortable making a BC break, however small it is :( Is this something that is absolutely required?

**Comment by blankse** [comment]
I created a Pass class in our standard bundle to set the searchThresholdValue to 9999:
https://gist.github.com/blankse/efd61a7aa4f95c29adb9f01eeff9f8a7

So I don't need this PR anymore ;)

**Comment by emodric** [comment]
I'm glad you found the solution to your problem :)

**Pull request closed without merging**
